### ISSUE TITLE
pillar.example does not use lookup

### ISSUE THREAD

**Issue by dahrens** [saltstack-formulas/couchdb-formula#3]
but the formula expects the values to be overwritten through lookup

``` yaml
couchdb:
  lookup:
    version: 1.6.1
```
